In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [43]:
torch.manual_seed(1)

In [44]:
class LogisticRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        return self.sigmoid(self.linear(x))

In [49]:
x_data = torch.FloatTensor([[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]])
y_data = torch.FloatTensor([[0], [0], [0], [1], [1], [1]])
print(x_data.shape)
print(y_data.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [46]:
model = LogisticRegressionModel()
optimizer = optim.SGD(model.parameters(),lr=1)

In [48]:
epochs = 100
for epoch in range(epochs+1):
    
    pred = model(x_data)
    cost = F.binary_cross_entropy(pred, y_data)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%10==0:
        p = pred>=torch.FloatTensor([0.5])
        corr = p.float() == y_data
        acc = corr.sum().item() / len(corr)
        print('Epoch:{:4d}/{} Cost: {:.6f} Acc {:2.2f}%'.format(epoch,epochs,cost.item(),acc*100))

tensor([[0.0240],
        [0.1476],
        [0.2739],
        [0.7967],
        [0.9491],
        [0.9836]], grad_fn=<SigmoidBackward>)
Epoch:   0/100 Cost: 0.133369 Acc 100.00%
tensor([[0.0211],
        [0.1427],
        [0.2557],
        [0.8051],
        [0.9536],
        [0.9851]], grad_fn=<SigmoidBackward>)
Epoch:  10/100 Cost: 0.124978 Acc 100.00%
tensor([[0.0185],
        [0.1378],
        [0.2401],
        [0.8129],
        [0.9577],
        [0.9864]], grad_fn=<SigmoidBackward>)
Epoch:  20/100 Cost: 0.117600 Acc 100.00%
tensor([[0.0164],
        [0.1330],
        [0.2265],
        [0.8200],
        [0.9613],
        [0.9877]], grad_fn=<SigmoidBackward>)
Epoch:  30/100 Cost: 0.111060 Acc 100.00%
tensor([[0.0146],
        [0.1284],
        [0.2143],
        [0.8265],
        [0.9644],
        [0.9888]], grad_fn=<SigmoidBackward>)
Epoch:  40/100 Cost: 0.105223 Acc 100.00%
tensor([[0.0130],
        [0.1241],
        [0.2034],
        [0.8326],
        [0.9672],
        [0.9897]], g