# Intro to Tensors

Tensors:
|T| = (batch size, length, dimension)

## Imports

In [2]:
import numpy as np
import torch

## Numpy Arrays

In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [7]:
print('Rank: ', t.ndim)
print('Shape: ', t.shape)

Rank:  1
Shape:  (7,)


## Pytorch Arrays

In [8]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [11]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [12]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [17]:
print(t.dim())
print(t.size())
print(t[:,2])

2
torch.Size([4, 3])
tensor([ 3.,  6.,  9., 12.])


## Operators

### Matmul

In [54]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of m1: ', m1.size())
print('Shape of m2: ', m2.size())
print(m1.matmul(m2))

Shape of m1:  torch.Size([2, 2])
Shape of m2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


### Mean

In [22]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [23]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [27]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [29]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [30]:
print(t.sum())
print(t.sum(dim=0))

tensor(10.)
tensor([4., 6.])


### Max and Argmax

In [31]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [32]:
print(t.max())
print(t.max(dim=0))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


### View

In [33]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])

ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [41]:
print(ft.view([3, 4]))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


### Squeeze

In [50]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [43]:
print(ft.squeeze())

tensor([0., 1., 2.])


In [52]:
print(ft.squeeze().unsqueeze(0).squeeze())

tensor([0., 1., 2.])


### Scatter

In [55]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [61]:
one_hot = torch.zeros(4, 3)
one_hot.scatter_(-1, lt ,1)
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### Concentration

In [62]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [63]:
print(torch.cat([x, y], dim = 0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [64]:
print(torch.cat([x, y], dim = 1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [65]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [72]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros Like

In [73]:
print(torch.ones_like(torch.FloatTensor([4,4])))

tensor([1., 1.])
